name: Formatting Check

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # 1️⃣ Checkout repository
      # -------------------------
      - uses: actions/checkout@v6

      # -------------------------
      # 2️⃣ Clang-format style check
      # https://github.com/marketplace/actions/clang-format-check
      # -------------------------
      - name: Run clang-format style check for C/C++/Protobuf
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: '22'
          check-path: 'src'

      # -------------------------
      # 3️⃣ EditorConfig check
      # https://github.com/marketplace/actions/editorconfig-checker-action
      # -------------------------
      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run editorconfig-checker
        run: editorconfig-checker
